export enum VehicleStatus {
  // FASE 1 — INGRESO CONTABLE
  POR_ARRIBAR = 'POR_ARRIBAR',

  // FASE 2 — MATRICULACIÓN
  ENVIADO_A_MATRICULAR = 'ENVIADO_A_MATRICULAR',

  // FASE 3 — DOCUMENTACIÓN
  DOCUMENTACION_PENDIENTE = 'DOCUMENTACION_PENDIENTE',
  DOCUMENTADO = 'DOCUMENTADO',

  // FASE 4 — CERTIFICACIÓN FÍSICA
  CERTIFICADO_STOCK = 'CERTIFICADO_STOCK',

  // FASE 5 — ACCESORIZACIÓN
  ORDEN_GENERADA = 'ORDEN_GENERADA',
  ASIGNADO = 'ASIGNADO',
  EN_INSTALACION = 'EN_INSTALACION',
  INSTALACION_COMPLETA = 'INSTALACION_COMPLETA',

  // FASE 6 — ENTREGA
  LISTO_PARA_ENTREGA = 'LISTO_PARA_ENTREGA',
  AGENDADO = 'AGENDADO',
  ENTREGADO = 'ENTREGADO',

  // ESTADOS DE EXCEPCIÓN
  REAPERTURA_OT = 'REAPERTURA_OT',
  CEDIDO = 'CEDIDO',
}
