export enum VehicleStatus {
  // FASE 1 — INGRESO Y CERTIFICACIÓN
  RECEPCIONADO = 'RECEPCIONADO',
  CERTIFICADO_STOCK = 'CERTIFICADO_STOCK',

  // FASE 2 — DOCUMENTACIÓN
  DOCUMENTACION_PENDIENTE = 'DOCUMENTACION_PENDIENTE',
  DOCUMENTADO = 'DOCUMENTADO',

  // FASE 3 — ACCESORIZACIÓN
  ORDEN_GENERADA = 'ORDEN_GENERADA',
  ASIGNADO = 'ASIGNADO',
  EN_INSTALACION = 'EN_INSTALACION',
  INSTALACION_COMPLETA = 'INSTALACION_COMPLETA',

  // FASE 4 — ENTREGA
  LISTO_PARA_ENTREGA = 'LISTO_PARA_ENTREGA',
  AGENDADO = 'AGENDADO',
  ENTREGADO = 'ENTREGADO',

  // ESTADOS DE EXCEPCIÓN
  REAPERTURA_OT = 'REAPERTURA_OT',
  CEDIDO = 'CEDIDO',
}
